### ISSUE TITLE
Couldnt include file "shared.lua"

### ISSUE THREAD

**Issue by sword134** [Lexa013/disguise-swep#1]
Just downloaded the addon and it throws this in the console.

Couldn't include file 'shared.lua' (File not found) (@addons/disguise_swep_main/lua/weapons/swep_disguise/cl_init.lua (line 1))

**Comment by Lexa013** [comment]
I can safely ignore this error, I'm gonna fix it today

**Comment by sword134** [comment]
@Lexa013 problem is that the swep doesnt load in the game because of that

**Comment by Lexa013** [comment]
The swep isn't in the spawnlist ?

**Comment by Lexa013** [comment]
I've updated the addon and it should be patched now, be sure to configure the addon (shared.lua)
